apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:

      - job_name: 'auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service:8081']

      - job_name: 'profile-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['profile-service:8082']

      - job_name: 'home-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['home-service:8083']

      - job_name: 'notification-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification-service:8084']


      # MySQL Exporter для auth-service
      - job_name: 'mysql-auth'
        static_configs:
          - targets: ['mysql-auth-exporter:9104']

      # MySQL Exporter для profile-service
      - job_name: 'mysql-profile'
        static_configs:
          - targets: ['mysql-profile-exporter:9104']