version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: authservice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: authservice
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8090:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: