
networks:
  auth-net:
    driver: bridge

services:

  mysql:
    image: mysql:8.0
    container_name: authservice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: authservice
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth-net

  prometheus:
    image: prom/prometheus
    container_name: service-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - mysql
    networks:
      - auth-net

  grafana:
    image: grafana/grafana
    container_name: service-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - auth-net

volumes:
  mysql_data:
  grafana_data: